import './globals.css';

import type { Metadata } from 'next';

import { NextUIProviders } from '@/providers';
import { LocalFontProviders } from '@/providers/LocalFontProviders';

export const metadata: Metadata = {
  title: 'Ocean Script',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ja'>
      <body>
        <NextUIProviders>
          <LocalFontProviders>{children}</LocalFontProviders>
        </NextUIProviders>
      </body>
    </html>
  );
}
